import type { ToolEventPayload } from '../claude.js';
// Re-export for convenience — adapters import from core/interfaces instead of claude directly
export type { ToolEventPayload } from '../claude.js';

/** Streaming responder for one in-progress Claude response */
export interface IStreamingResponder {
  onTextDelta(text: string): void;
  onToolEvent(event: ToolEventPayload): void;
  finish(): Promise<void>;
  getFullText(): string;
  /** Called after the Claude process is spawned, providing a kill function for cancellation */
  onProcessSpawned?(kill: () => void): void;
}

/**
 * Adapter-provided interface for delivering responses back to the user.
 * One instance per queued message.
 * Lifecycle: onProcessing() -> [Claude runs] -> onComplete() | onError()
 */
export interface ChannelResponder {
  /** Signal that processing has started (e.g., Slack hourglass reaction) */
  onProcessing(): Promise<void>;

  /** Signal successful completion (e.g., Slack checkmark reaction) */
  onComplete(): Promise<void>;

  /** Report a fatal error to the user */
  onError(message: string): Promise<void>;

  /** Send a complete text response (used in batch mode) */
  sendResponse(text: string): Promise<void>;

  /** Create a streaming responder for this message's response */
  createStreamingResponder(): IStreamingResponder;

  /** Post-processing after streaming finishes (e.g., oversized response file upload fallback) */
  onStreamComplete(fullText: string, responder: IStreamingResponder): Promise<void>;

  /** Upload a file attachment generated by Claude */
  uploadFile(filePath: string): Promise<void>;

  /** Post a non-fatal warning to the user */
  warn(message: string): Promise<void>;
}
