import type { ToolEventPayload, SessionState } from '../claude.js';
import type { QueuedMessage } from '../queue.js';
// Re-export for convenience — adapters import from core/interfaces instead of claude directly
export type { ToolEventPayload } from '../claude.js';
export type { SessionState } from '../claude.js';

/**
 * Adapter hook for render-at-processing-time prompts. The engine invokes it
 * from processQueuedMessage() AFTER resolving cwd/worktree/session — the
 * adapter never derives session ids or artifact paths itself (artifact paths
 * encode the resolved worktree cwd). Only consulted for structured entries
 * (queued.slack present); legacy pre-rendered `text` passes through untouched.
 */
export interface PromptCoordinator {
  /**
   * Render the final prompt for this turn. `session.resuming` mirrors the
   * --resume decision. `ctx.sessionTempDir` is the resolved per-session temp
   * dir (already created by the engine) — the coordinator downloads inbound
   * files into its `incoming/` at processing time (D10). Any non-fatal
   * download issues are returned as `warnings`, which the engine forwards to
   * `responder.warn` so a failed/oversized download degrades gracefully
   * instead of throwing or silently dropping the file.
   */
  prepare(
    queued: QueuedMessage,
    session: SessionState,
    ctx: { sessionTempDir: string },
  ): Promise<{ text: string; warnings?: string[] }>;
  /**
   * Called only after the runner resolves successfully — advances the Slack
   * history watermark. Failed turns must NOT advance it: re-injecting is
   * benign duplication, advancing would risk silent loss.
   */
  onTurnCommitted(queued: QueuedMessage, session: SessionState): Promise<void>;
}

/** How a streamed turn ended — passed to {@link IStreamingResponder.finish}. */
export interface StreamOutcome {
  ok: boolean;
  /** Scrubbed error message when `ok` is false. */
  errorMessage?: string;
}

/** Streaming responder for one in-progress Claude response */
export interface IStreamingResponder {
  onTextDelta(text: string): void;
  /**
   * Extended-thinking (reasoning) deltas, surfaced separately from the final
   * answer text. Optional — responders that have no "working notes" surface
   * (e.g. voice) may omit it.
   */
  onReasoningDelta?(text: string): void;
  onToolEvent(event: ToolEventPayload): void;
  /**
   * Finalize the live stream. ALWAYS called exactly once per turn — on the
   * success path before `onStreamComplete`, and from the engine's cleanup with
   * `{ok: false}` when the runner threw — so the live UI can never be left
   * dangling/expanded. Responders that don't distinguish outcomes ignore the arg.
   */
  finish(outcome?: StreamOutcome): Promise<void>;
  getFullText(): string;
  /** Called after the Claude process is spawned, providing a kill function for cancellation */
  onProcessSpawned?(kill: () => void): void;
}

/**
 * Adapter-provided interface for delivering responses back to the user.
 * One instance per queued message.
 * Lifecycle: onProcessing() -> [Claude runs] -> onComplete() | onError()
 */
export interface ChannelResponder {
  /** Signal that processing has started (e.g., Slack hourglass reaction) */
  onProcessing(): Promise<void>;

  /** Signal successful completion (e.g., Slack checkmark reaction) */
  onComplete(): Promise<void>;

  /** Report a fatal error to the user */
  onError(message: string): Promise<void>;

  /** Send a complete text response (used in batch mode) */
  sendResponse(text: string): Promise<void>;

  /** Create a streaming responder for this message's response */
  createStreamingResponder(): IStreamingResponder;

  /**
   * Post-processing after a SUCCESSFUL stream (never called on the error path —
   * that ends at `finish({ok: false})`). `finalText` is the clean final answer
   * (Claude's `result` text), which may differ from the responder's accumulated
   * `getFullText()` (the full live narration). When the `result` event was
   * missing (killed turn, clean exit mid-turn), the engine falls back to the
   * accumulated text and sets `opts.authoritative` to false — adapters should
   * then trust the live message rather than re-deliver.
   */
  onStreamComplete(
    finalText: string,
    responder: IStreamingResponder,
    opts?: { authoritative?: boolean },
  ): Promise<void>;

  /** Upload a file attachment generated by Claude */
  uploadFile(filePath: string): Promise<void>;

  /** Post a non-fatal warning to the user */
  warn(message: string): Promise<void>;
}
